### ISSUE TITLE
Membership Contact Role Naming Convention

### ISSUE THREAD

**Issue by RealEvanPonter** [SFDO-Community-Sprints/MembershipSchemaAndBenefits#13]
Develop a quick action that sets the name of the Membership Contact Role object.

ACs:

- There is a Quick Action on the Membership that sets the Name of the Membership Contact Role created to be `{! Membership.Name } - {! YEAR(TODAY()) }`
- The Quick Action prepopulates the Start Date with today's date. 
- The Quick Action's layout exposes the Contact lookup, Start Date, End Date, Is Primary, and Role fields.

**Comment by RealEvanPonter** [comment]
@davidmreed I set up:

- "New Membership Contact Role" action on the Membership object
- Added the Membership related list to the "Contact" page layout
- Created a "Membership" lightning app

**Comment by davidmreed** [comment]
@RealEvanPonter I'll grab your work and push it into a PR.
