### ISSUE TITLE
Build automation for Household-associated Contact Role management

### ISSUE THREAD

**Issue by davidmreed** [SFDO-Community-Sprints/MembershipSchemaAndBenefits#18]
ACs:

- When we create a Membership that is associated with an NPSP Household Account, automatically create Membership Contact Roles for each Household member, based on a specific Membership Type identified by a Custom Setting. [Membership trigger on `insert`]
- When a Contact is removed from their Household, change the End Date of any Contact Membership Roles which are (1) current; (2) associated with a Household membership type on the former Household. [Contact trigger on update]
- When a Contact is added to a new Household, add Contact Membership Roles for memberships that are (1) active and (2) of Household membership type. Set the Start Date on the Contact Membership Role to today. [Contact trigger on insert, update]
- When a Contact is merged, handle their memberships appropriately as per the above roles. [Contact trigger on after delete]

**Comment by D-McGovern** [comment]
Update - don't need to specify NPSP Household account functionality; just any Account with direct Contact relationships
