### ISSUE TITLE
Rename "master" branch

### ISSUE THREAD

**Issue by tet3** [SFDO-Community-Sprints/MembershipSchemaAndBenefits#37]
This repo is still using `master` as the default/primary branch, and should switch to `main`.

**Comment by kreynen** [comment]
While I understand the motivation for moving to master, we need to confirm that Metecho will work with Main or Master. We got stuck on https://github.com/SFDO-Tooling/Metecho/issues/2083 for a bit and I'd like to make sure everything is running smoothly before the [next virtual community sprint March 29 & 30](https://docs.google.com/forms/d/e/1FAIpQLSc6GjUKbTYaJZy2_JNPk9RL6ljYHxpj0o4wwT3lxlpMtlA7vQ/viewform).
