### ISSUE TITLE
Basic Point and Click Permission Changes (e.g. basic permissions)

### ISSUE THREAD

**Issue by paulginsberg** [SFDO-Community-Sprints/MembershipSchemaAndBenefits#51]
- System Administrator access to Membership object
- System Administrator access to Membership Contact Role object
- Create Membership Full Permissions permission set with:
- Membership Full Permissions permission set: full CRED permissions on Membership object
- Membership Full Permissions permission set: full CRED permissions on Membership Contact Role object
- Create Membership App with Membership object

**Comment by paulginsberg** [comment]
Membership permission set already exists but was not assigned. So minor improvements implemented in this Sprint are:

-> updated permission set (object x2)
-> updated permission set description
-> added Membership as an assigned app to the Membership permission set
-> added Membership as an assigned app to the System Administrator profile

**Comment by D-McGovern** [comment]
Closed, with the exception of adding membership permissions to the system admin profile - this is not straightforward and has been postponed into another Issue
