### ISSUE TITLE
Prepare for May 2023 Sprint

### ISSUE THREAD

**Issue by tobiasaw34002** [SFDO-Community-Sprints/MembershipSchemaAndBenefits#92]
Hi Guys, 
Cori is looking for a Jobs to be done for the NY Sprint. 

@kreynen  You mentioned wanting to focus on getting the Pages site published. Anything else @selfuntitled ? 

I need to get her something tonight. 

Does this work - 
Our main focus for this sprint will be migrating documentation from our wiki to a git hub pages site to make it more accessible and user friendly.

**Comment by tobiasaw34002** [comment]
@eramirez-arkus Are you going to the sprint? Anything to add?

**Comment by eramirez-arkus** [comment]
Nope. I'm traveling home on Friday.

**Comment by allisonletts** [comment]
@tobiasaw34002 closing this since the sprint happened.
